
// This file has been generated by the GUI designer. Do not modify.
namespace JLib
{
	public partial class Board
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action FileAction;

		private global::Gtk.Action ZoomAction;

		private global::Gtk.Action ViewPointAction;

		private global::Gtk.Action ScalingAction;

		private global::Gtk.Action ExtraAction;

		private global::Gtk.Action SaveImageAction;

		private global::Gtk.Action SaveImageAsAction;

		private global::Gtk.Action ExitAction;

		private global::Gtk.Action InAction;

		private global::Gtk.Action OutAction;

		private global::Gtk.Action goLeftAction;

		private global::Gtk.Action goRightAction;

		private global::Gtk.Action goUpAction;

		private global::Gtk.Action goDownAction;

		private global::Gtk.Action smallLeftAction;

		private global::Gtk.Action smallRightAction;

		private global::Gtk.Action smallUpAction;

		private global::Gtk.Action smallDownAction;

		private global::Gtk.Action NewAction;

		private global::Gtk.Action OriginalAction;

		private global::Gtk.Action X0Action;

		private global::Gtk.Action X1Action;

		private global::Gtk.Action X2Action;

		private global::Gtk.Action X3Action;

		private global::Gtk.Action X4Action;

		private global::Gtk.Action X5Action;

		private global::Gtk.Action X6Action;

		private global::Gtk.Action X7Action;

		private global::Gtk.Action X8Action;

		private global::Gtk.Action X9Action;

		private global::Gtk.VBox vboxBase;

		private global::Gtk.MenuBar Menu;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget JLib.Board
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.ZoomAction = new global::Gtk.Action ("ZoomAction", global::Mono.Unix.Catalog.GetString ("Zoom"), null, null);
			this.ZoomAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Zoom");
			w1.Add (this.ZoomAction, null);
			this.ViewPointAction = new global::Gtk.Action ("ViewPointAction", global::Mono.Unix.Catalog.GetString ("ViewPoint"), null, null);
			this.ViewPointAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("ViewPoint");
			w1.Add (this.ViewPointAction, null);
			this.ScalingAction = new global::Gtk.Action ("ScalingAction", global::Mono.Unix.Catalog.GetString ("Scaling"), null, null);
			this.ScalingAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Scaling");
			w1.Add (this.ScalingAction, null);
			this.ExtraAction = new global::Gtk.Action ("ExtraAction", global::Mono.Unix.Catalog.GetString ("Extra"), null, null);
			this.ExtraAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Extra");
			w1.Add (this.ExtraAction, null);
			this.SaveImageAction = new global::Gtk.Action ("SaveImageAction", global::Mono.Unix.Catalog.GetString ("Save Image"), null, null);
			this.SaveImageAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save Image");
			w1.Add (this.SaveImageAction, null);
			this.SaveImageAsAction = new global::Gtk.Action ("SaveImageAsAction", global::Mono.Unix.Catalog.GetString ("Save Image As"), null, null);
			this.SaveImageAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save Image As");
			w1.Add (this.SaveImageAsAction, null);
			this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, null);
			this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
			w1.Add (this.ExitAction, null);
			this.InAction = new global::Gtk.Action ("InAction", global::Mono.Unix.Catalog.GetString ("In"), null, null);
			this.InAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("In");
			w1.Add (this.InAction, null);
			this.OutAction = new global::Gtk.Action ("OutAction", global::Mono.Unix.Catalog.GetString ("Out"), null, null);
			this.OutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Out");
			w1.Add (this.OutAction, null);
			this.goLeftAction = new global::Gtk.Action ("goLeftAction", global::Mono.Unix.Catalog.GetString ("go Left"), null, null);
			this.goLeftAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("go Left");
			w1.Add (this.goLeftAction, null);
			this.goRightAction = new global::Gtk.Action ("goRightAction", global::Mono.Unix.Catalog.GetString ("go Right"), null, null);
			this.goRightAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("go Right");
			w1.Add (this.goRightAction, null);
			this.goUpAction = new global::Gtk.Action ("goUpAction", global::Mono.Unix.Catalog.GetString ("go Up"), null, null);
			this.goUpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("go Up");
			w1.Add (this.goUpAction, null);
			this.goDownAction = new global::Gtk.Action ("goDownAction", global::Mono.Unix.Catalog.GetString ("go Down"), null, null);
			this.goDownAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("go Down");
			w1.Add (this.goDownAction, null);
			this.smallLeftAction = new global::Gtk.Action ("smallLeftAction", global::Mono.Unix.Catalog.GetString ("small Left"), null, null);
			this.smallLeftAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("small Left");
			w1.Add (this.smallLeftAction, null);
			this.smallRightAction = new global::Gtk.Action ("smallRightAction", global::Mono.Unix.Catalog.GetString ("small Right"), null, null);
			this.smallRightAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("small Right");
			w1.Add (this.smallRightAction, null);
			this.smallUpAction = new global::Gtk.Action ("smallUpAction", global::Mono.Unix.Catalog.GetString ("small Up"), null, null);
			this.smallUpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("small Up");
			w1.Add (this.smallUpAction, null);
			this.smallDownAction = new global::Gtk.Action ("smallDownAction", global::Mono.Unix.Catalog.GetString ("small Down"), null, null);
			this.smallDownAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("small Down");
			w1.Add (this.smallDownAction, null);
			this.NewAction = new global::Gtk.Action ("NewAction", global::Mono.Unix.Catalog.GetString ("New"), null, null);
			this.NewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New");
			w1.Add (this.NewAction, null);
			this.OriginalAction = new global::Gtk.Action ("OriginalAction", global::Mono.Unix.Catalog.GetString ("Original"), null, null);
			this.OriginalAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Original");
			w1.Add (this.OriginalAction, null);
			this.X0Action = new global::Gtk.Action ("X0Action", global::Mono.Unix.Catalog.GetString ("X0"), null, null);
			this.X0Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("X0");
			w1.Add (this.X0Action, null);
			this.X1Action = new global::Gtk.Action ("X1Action", global::Mono.Unix.Catalog.GetString ("X1"), null, null);
			this.X1Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("X1");
			w1.Add (this.X1Action, null);
			this.X2Action = new global::Gtk.Action ("X2Action", global::Mono.Unix.Catalog.GetString ("X2"), null, null);
			this.X2Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("X2");
			w1.Add (this.X2Action, null);
			this.X3Action = new global::Gtk.Action ("X3Action", global::Mono.Unix.Catalog.GetString ("X3"), null, null);
			this.X3Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("X3");
			w1.Add (this.X3Action, null);
			this.X4Action = new global::Gtk.Action ("X4Action", global::Mono.Unix.Catalog.GetString ("X4"), null, null);
			this.X4Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("X4");
			w1.Add (this.X4Action, null);
			this.X5Action = new global::Gtk.Action ("X5Action", global::Mono.Unix.Catalog.GetString ("X5"), null, null);
			this.X5Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("X5");
			w1.Add (this.X5Action, null);
			this.X6Action = new global::Gtk.Action ("X6Action", global::Mono.Unix.Catalog.GetString ("X6"), null, null);
			this.X6Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("X6");
			w1.Add (this.X6Action, null);
			this.X7Action = new global::Gtk.Action ("X7Action", global::Mono.Unix.Catalog.GetString ("X7"), null, null);
			this.X7Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("X7");
			w1.Add (this.X7Action, null);
			this.X8Action = new global::Gtk.Action ("X8Action", global::Mono.Unix.Catalog.GetString ("X8"), null, null);
			this.X8Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("X8");
			w1.Add (this.X8Action, null);
			this.X9Action = new global::Gtk.Action ("X9Action", global::Mono.Unix.Catalog.GetString ("X9"), null, null);
			this.X9Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("X9");
			w1.Add (this.X9Action, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "JLib.Board";
			this.Title = global::Mono.Unix.Catalog.GetString ("Board");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DestroyWithParent = true;
			// Container child JLib.Board.Gtk.Container+ContainerChild
			this.vboxBase = new global::Gtk.VBox ();
			this.vboxBase.Name = "vboxBase";
			this.vboxBase.Spacing = 6;
			// Container child vboxBase.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='Menu'><menu name='FileAction' action='FileAction'><menuitem name='SaveImageAction' action='SaveImageAction'/><menuitem name='SaveImageAsAction' action='SaveImageAsAction'/><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='ZoomAction' action='ZoomAction'><menuitem name='InAction' action='InAction'/><menuitem name='OutAction' action='OutAction'/></menu><menu name='ViewPointAction' action='ViewPointAction'><menuitem name='goLeftAction' action='goLeftAction'/><menuitem name='goRightAction' action='goRightAction'/><menuitem name='goUpAction' action='goUpAction'/><menuitem name='goDownAction' action='goDownAction'/><separator/><menuitem name='smallLeftAction' action='smallLeftAction'/><menuitem name='smallRightAction' action='smallRightAction'/><menuitem name='smallUpAction' action='smallUpAction'/><menuitem name='smallDownAction' action='smallDownAction'/></menu><menu name='ScalingAction' action='ScalingAction'><menuitem name='NewAction' action='NewAction'/><menuitem name='OriginalAction' action='OriginalAction'/></menu><menu name='ExtraAction' action='ExtraAction'><menuitem name='X0Action' action='X0Action'/><menuitem name='X1Action' action='X1Action'/><menuitem name='X2Action' action='X2Action'/><menuitem name='X3Action' action='X3Action'/><menuitem name='X4Action' action='X4Action'/><menuitem name='X5Action' action='X5Action'/><menuitem name='X6Action' action='X6Action'/><menuitem name='X7Action' action='X7Action'/><menuitem name='X8Action' action='X8Action'/><menuitem name='X9Action' action='X9Action'/></menu></menubar></ui>");
			this.Menu = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/Menu")));
			this.Menu.Name = "Menu";
			this.vboxBase.Add (this.Menu);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxBase[this.Menu]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			this.Add (this.vboxBase);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 590;
			this.DefaultHeight = 498;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
